version: "3"

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/dev.Dockerfile
    volumes:
      - .:/app:Z
    command: sleep infinity

volumes:
  deribit-history-client:
